- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker

  - name: Deploy Docker Container
    command: docker run -itd -p 8089:8081 udaydocker123/bankingfproject:latest
  - name: Deploy Docker Container
    command: docker run -itd --name prometheus -p 9090:9090 bitnami/prometheus
  - name: Deploy Docker Container
    command: docker run -itd --name grafana -p 3000:3000 grafana/grafana
